root: true

env:
  node: true

parser: '@typescript-eslint/parser'

plugins:
  - '@typescript-eslint'

extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'

rules:
  'comma-dangle': ['error', 'always-multiline']
  'indent': ['error', 2]
  '@typescript-eslint/no-unused-vars': [error, { 'argsIgnorePattern': '^_' }]
  'quotes': ['error', 'single']
  'semi': ['error', 'always']
  'object-curly-spacing': ['error', 'always']
